### ISSUE TITLE
Cannot get SPDLOG_VERSION from common.h.

### ISSUE THREAD

**Issue by GetAGripGal** [zeroxs/aegis.cpp#36]
When i run cmake i get the error:

`CMake Error at cmake/FindSpdlog.cmake:16 (message):
  Cannot get SPDLOG_VERSION from common.h.
Call Stack (most recent call first):
  CMakeLists.txt:36 (find_package)`

i installed spdlog and the other dependencies.

**Comment by zeroxs** [comment]
Did you clone the repo recursively? You either need to clone recursively or have spdlog in an accessible location for cmake.

**Comment by nandemonogatari** [comment]
make sure to use the specific branch zeroxs uses if you install manually, the default spdlog v1.x branch doesnt have the SPDLOG_VERSION in common.h

**Comment by NexAdn** [comment]
Which branch to use? I don't see a specific branch being required anywhere. Also, the CMakeLists accepts anything above 0.16.4, so I gotta assume the v1.x branch should be working perfectly fine. Also, the .gitmodules does not specify any certain commit or branch to use and the default branch of the spdlog repository is v1.x (but I assume git might still be using the master branch).

Is there anything in the v1.x branch which makes aegis break so that it cannot be built with the v1.x branch or is the problem really just having to patch the FindSpdlog.cmake? If one really shouldn't use the v1.x branch for whatever reason, I suggest stating so in the README.

**Comment by zeroxs** [comment]
it most certainly does specify a specific commit. it links to https://github.com/gabime/spdlog/tree/71e93a4f2d52fb9f9dafdeea7386bf0c780981e3
you can see this when you view https://github.com/zeroxs/aegis.cpp/tree/master/lib
that commit for spdlog was done in 2018.

I do agree though that it should be in plain text in the readme that it targets an older version. When I first made this, that was the latest version and they only recently did a huge overhaul.

**Comment by zeroxs** [comment]
Should be fixed with https://github.com/zeroxs/aegis.cpp/commit/536b3d4587fa0e83104c9455e5ffd66d7041dcdc
