### ISSUE TITLE
Saying hi ...

### ISSUE THREAD

**Issue by bsergean** [zeroxs/aegis.cpp#47]
Hi there,

I'm the author of a websocket C++ library (with also http support) which has been used by other libraries already to talk to discord (you can see which ones at the bottom of the landing page). If you want to give it a try it is here -> https://github.com/machinezone/IXWebSocket

I am very biased because I wrote it ... but one thing I like about it is that it has few dependencies (zlib + a tls backend) ; it does not depend on boost so people usually find it easy to integrate in their project, and it is not too low level and uses C++11 threads etc... with callbacks.

Ciao and good luck with your library !

(this really would belong more to a 'discussion', but using a github issue instead)

**Comment by Znunu** [comment]
I'm not really affiliated with this repo, just wanted to wish you luck with your lib too! I hope it finds even more use ;3

**Comment by bsergean** [comment]
Thanks @Znunu / I can see you have a very successul and loved python discord library, congratulations about this :)

**Comment by zeroxs** [comment]
@bsergean I'm not sure what makes this acceptable practice. If you had a suggestion for me, you can always contact me in Discord listed in this repo, or by email listed on my profile. Just throwing ads in an issue is tasteless. For the record, I have tried your library and I did not like it which is why I don't use it. I also do not depend on Boost.

**Comment by bsergean** [comment]
I do not use discord nor did I see, or thought about searching for your email, and thought it would be ok to create issues to suggest this. I'm sorry this seems to have created stress for you.

I'm curious about what you didn't like in the library, but I don't want to create more stress, so I'm glad that you closed the ticket and that we can both move on with our life !

**Comment by zeroxs** [comment]
If you had suggested your library as a way to improve mine, that would have been different, but instead you just made an issue saying you have bias about it with no real reasoning on why I should switch.

One thing in specific is PascalCase. Sounds weird, but I avoid libraries that do not follow the established standard set by stdlib and Boost unless there really is no other option. Since asio exists, is being added to the stdlib, and is very functional, along with websockets++, I use them.

**Comment by Znunu** [comment]
lmaooo, I _wish_ I had wrote discord.py but nah, those credits go to the legend Rapptz
