### ISSUE TITLE
aegis::guild::member_has_role gives wrong information

### ISSUE THREAD

**Issue by VanModers** [zeroxs/aegis.cpp#66]
aegis::guild::member_has_role function always returns false for the bot, except right after the roles are changed on server side. For other users it only returns true for the role @everyone and false for everything else. This has worked in the past. Here is my code:
```
void showRoles(aegis::gateway::objects::message m) {
	unordered_map<aegis::snowflake, aegis::gateway::objects::role> roles = m.get_guild().get_roles();
	for (pair<aegis::snowflake, aegis::gateway::objects::role> role : roles) {
		cout << role.second.name << endl;
		unordered_map<aegis::snowflake, aegis::user*> members = m.get_guild().get_members();
		for (pair<aegis::snowflake, aegis::user*> member : members) {
			cout << member.second->get_full_name() << ": ";
			if (m.get_guild().member_has_role(member.second->get_id(), role.second.id) == true)
				cout << "True" << endl;
			else
				cout << "False" << endl;
		}
		cout << endl;
	}
}
```

**Comment by zeroxs** [comment]
That is because the role code requires privileged intents to function. Without them, the bot only receives info from users that get updated while the bot is online. This is due to the v8 change Discord made in the gateway forcing intents. Fwiw, v6 (which is what aegis.cpp requests) should still function without general intents, but I do believe it still requires privileged intents to receive that data.

**Comment by VanModers** [comment]
Thanks for the quick response. I gave my bot the privileged intents it needed, and now it's working.
